font_family = "Noto Sans"
background = "#232627"
foreground = "#FCFCFC"
label = "#EFF0F1"
muted = "#7F8C8D"
font_small = 10
font_normal = 12
font_large = 18
green = "#11D116"
cyan = "#1ABC9C"
amber = "#F67400"
red = "#ED1515"
violet = "#9B59B6"
led_on = "#1CDC9A"
graph_background = "#000000"
graph_background_opacity = 0.2

[[header]]
slot = "time-left"
icon = ""
command = "@menu"
color = "#5fd75f"

[[header]]
slot = "time-right"
icon = ""
command = "loginctl lock-session"
color = "#d4af37"
